openapi: "3.0.1"
info:
  title: "aws-serverless"
  version: "1.0"
  description: "An example of a serverless application"
servers:
  - url: "https://8bgmut0ajj.execute-api.ap-northeast-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "Prod"
paths:
  /tasks/{id}:
    get:
      tags:
        - TASKS
      responses:
        "200":
          description: "Default response for GET /tasks/{id}"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      summary: "Get task by ID"
      description: "Returns a task by ID"
      operationId: "getById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:465068362057:function:aws-serverless-TasksGetFunction-34mkEI7AkSd9/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

  /tasks:
    post:
      tags:
        - TASKS
      summary: "Create a new task"
      description: "Creates a new task with a unique ID and associated text."
      operationId: "createTask"
      requestBody:
        description: "Task creation request"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "201":
          description: "Task successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          description: "Invalid request"

      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:465068362057:function:aws-serverless-TasksPostFunction-R4zT1DCm82cN/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

components:
  schemas:
    Empty: {}

    TaskRequest:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Unique identifier for the task"
        text:
          type: "string"
          description: "The text content of the task"
      required:
        - id
        - text
    TaskResponse:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Unique identifier for the created task"
        text:
          type: "string"
          description: "The text content of the created task"
        createdAt:
          type: "string"
          format: "date-time"
          description: "Timestamp when the task was created"
